### ISSUE TITLE
impressum - nennung kreative

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/holzformart#11]
hatte noch eine kleine inhaltlihche anpassung des impressums vorgenommen, da sind wir als kreative genannt. liegt inne box.

Design, Fotografie, Projektkoordination

Corporate Design: 	Carola Tierling (http://www.carola-tierling.de/)
Webdesign: 			Matteng  (http://matteng.de)
Fotografie:	 		Steffen Höft (http://www.steffen-hoeft.de/)
Projektkoordination: 	MEA Studio (https://meastudio.de/)

![image](https://cloud.githubusercontent.com/assets/19430535/23377141/16d99696-fd2f-11e6-97e1-1c4f38beed6e.png)

**Comment by Matteng123** [comment]
je nachdem wie die textlinks bei dir rauskommen und ggfs rot sind brauchst du das nicht zwingend an mein design anzupassen. reinbauen und feddich.

**Comment by kremin** [comment]
ach what die carola. so klein die welt. :)

**Comment by Matteng123** [comment]
haha. ihr kennt euch? wie witzig. mit ihr teile ich mir aktuell meinen büro arbeitsplatz. sie hat die broschüre gemacht und wir quasi zusammen die überarbeitung.

**Comment by kremin** [comment]
kennen von der fh. mehr auch nicht. sie ist mir im gedächnis geblieben weil sie eine schöne person und fähige designerin war/ist.
