### ISSUE TITLE
livegang DE (&EN)

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/holzformart#18]
morgen früh ist der domain-umzug abgeschlossen. dann pushen wir die DE-Seite schon hoch. bzw. wenn es klappt schon DE und EN. Zugangsdaten sind abgelegt: website\_material\zugang

**Comment by kremin** [comment]
Übersetzung fehlt:
Innenausbau:
- Räume neu denken und gestalten.

**Comment by kremin** [comment]
Über uns:
- Das sind wir: Holzformart
- Im Detail
- Wir wissen, Vertrauen bekommt man nicht geschenkt. Wir verdienen es uns.

**Comment by Matteng123** [comment]
Räume neu denken und gestalten: Rethinking and designing spaces

Das sind wir: Holzformart: This is us: Holzformart

Im Detail: Details

Wir wissen, Vertrauen bekommt man nicht geschenkt. Wir verdienen es uns.: 
We know that trust isn‘t handed to us on a plate. It‘s something that we earn.
