### ISSUE TITLE
mobile version auf iphone zerschossen

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/holzformart#19]
auf dem iphone gibts nen fehler. im dev-tool bei chrome geht alles nach plan, aber "in escht" zerschiesst sich die seite total.

**Comment by kremin** [comment]
Wo denn? Cache?

**Comment by Matteng123** [comment]
nee, glaube nicht. auf meinem safari macht der das gleiche - da hatte ich die seite noch nie auf. auch auf dem tablet zerschiesst sich die seite leider total.

**Comment by kremin** [comment]
iFrame?

**Comment by Matteng123** [comment]
hat sich erledigt, wir sind wieder auf dem alten server. ich schicke dir gleich nochmal die zugangsdaten!
