### ISSUE TITLE
Loader-Endlos-Schleife

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/holzformart#22]
beim safari (8.0.5) / ios x (10.10.3) kommt nur der loader, sonst nix. läd sich quasi nen wolf. komisch, denn die bugs auf 24-1 scheinen ja den selben browser zu betreffen. kann da ein zusammenhang bestehen?

**Comment by Matteng123** [comment]
sehe gerade: bei meinem ipad gibts den fehler sowohl auf dem chrome, als auch auf dem safari. dachte, es läge evtl. an den videos, die er nicht geladen bekommt. aber der bug besteht auch auf der kontakt.html, die ja sonst wenig inhalte hat.

auf meine iphone läuft das ding dafür sowohl auf dem safari, als auch auf dem chrome. komisch.

**Comment by Matteng123** [comment]
im IE kommt auch nur der endlos-loader

**Comment by kremin** [comment]
welches iOs auf dem iPad? Ich denke es hängt mit ES6 zusammen. Da fehlen ein paar Polyfills für die noch alten Browser. Das wird auch bei 24-1 das Thema sein. Bei mir läuft es auf allen 4 iPads aber die sind alle relativ aktuell mit iOs. Nur das 1er iPad wirft Fehler aber das ist irgendwann stehen geblieben im Support.

**Comment by kremin** [comment]
ich habe mal ein set ergänzt kann aber erst in 2 std checken und jetzt nur hochladen.

**Comment by kremin** [comment]
IE geht jetzt bis zum 10er runter. 11 und Edge ist makellos. Der 10er hat ein Thema mit dem Video weil er da den Flashplayer lädt. Das fixe ich noch.
