### ISSUE TITLE
safari positionierungen

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/holzformart#26]
der loader ist behoben, aber dafür bumst es diverse positionierungen im safari:

![image](https://cloud.githubusercontent.com/assets/19430535/23579155/81078e4a-00e7-11e7-93f6-a1010e8d3f1e.png)
![image](https://cloud.githubusercontent.com/assets/19430535/23579156/890e162c-00e7-11e7-8cdb-725de3136935.png)

**Comment by kremin** [comment]
safari teste ich gleich mal durch. ist aber nicht der aktuelle.
