### ISSUE TITLE
mitbewerber und architekten raus

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/holzformart#3]
das soll die konkurrenz nun doch nicht wissen ;)

**Comment by kremin** [comment]
Also nur die Kundenspalte?

**Comment by Matteng123** [comment]
hatte ich falsch im kopf. bitte nur die spalte "architekten und planer" entfernen. dafür die kundenspalte teilen und den freien platz dafür nutzen.

**Comment by kremin** [comment]
Und Architektn und Planer raus?
